import * as fs from "fs";
import * as path from "path";
import { exec } from "child-process-promise";
import type { GeneratedFile } from "../types/generated";

const BUILD_TIMEOUT = 120000; // 120 seconds
const MAX_CONCURRENT_BUILDS = 5;

interface BuildResult {
  success: boolean;
  jarPath?: string;
  error?: string;
  stdout?: string;
  stderr?: string;
}

export class BuildOrchestrator {
  private activeBuildCount = 0;
  private buildQueue: Array<() => Promise<BuildResult>> = [];

  /**
   * Generate mod and compile to JAR
   */
  async buildMod(files: GeneratedFile[], modId: string): Promise<BuildResult> {
    const tempDir = this.createTempDirectory(modId);

    try {
      // Write all generated files to disk
      this.writeFiles(files, tempDir);

      // Run gradle build
      const jarPath = await this.runGradleBuild(tempDir);

      return {
        success: true,
        jarPath,
      };
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      return {
        success: false,
        error: errorMessage,
      };
    } finally {
      // Cleanup temp directory
      try {
        this.cleanupDirectory(tempDir);
      } catch (e) {
        console.error("Failed to cleanup temp directory:", e);
      }
    }
  }

  /**
   * Create a temporary directory for this build
   */
  private createTempDirectory(modId: string): string {
    const timestamp = Date.now();
    const randomId = Math.random().toString(36).substring(7);
    const tempDir = path.join("/tmp/mods", `${modId}_${timestamp}_${randomId}`);

    fs.mkdirSync(tempDir, { recursive: true });
    return tempDir;
  }

  /**
   * Write all generated files to disk
   */
  private writeFiles(files: GeneratedFile[], baseDir: string): void {
    files.forEach((file) => {
      const fullPath = path.join(baseDir, file.path);
      const dir = path.dirname(fullPath);

      // Create directories if they don't exist
      fs.mkdirSync(dir, { recursive: true });

      // Write file
      if (typeof file.content === "string") {
        fs.writeFileSync(fullPath, file.content, "utf-8");
      } else if (Buffer.isBuffer(file.content)) {
        fs.writeFileSync(fullPath, file.content);
      }
    });
  }

  /**
   * Run gradle build in the temp directory
   */
  private async runGradleBuild(tempDir: string): Promise<string> {
    // Check if gradlew exists, if not, copy from system
    const gradlewPath = path.join(tempDir, "gradlew");

    if (!fs.existsSync(gradlewPath)) {
      // Create a minimal gradlew wrapper script
      this.createGradleWrapper(tempDir);
    }

    // Change to temp directory and run build
    const command = `cd "${tempDir}" && chmod +x gradlew && ./gradlew build --no-daemon`;

    try {
      const result = await exec(command, {
        timeout: BUILD_TIMEOUT,
        shell: "/bin/bash",
      });

      // Find the generated JAR
      const jarPath = this.findJar(tempDir);

      if (!jarPath) {
        throw new Error("JAR file not generated by build");
      }

      return jarPath;
    } catch (error) {
      const message =
        error instanceof Error
          ? error.message
          : "Build failed with unknown error";

      // Try to capture error log
      const errorLog = this.captureErrorLog(tempDir);
      throw new Error(
        `Gradle build failed: ${message}\n${errorLog}`.slice(0, 2000)
      );
    }
  }

  /**
   * Find the generated JAR file
   */
  private findJar(buildDir: string): string | null {
    const libDir = path.join(buildDir, "build", "libs");

    if (!fs.existsSync(libDir)) {
      return null;
    }

    const files = fs.readdirSync(libDir);
    const jarFile = files.find((f) => f.endsWith(".jar"));

    return jarFile ? path.join(libDir, jarFile) : null;
  }

  /**
   * Capture gradle error output
   */
  private captureErrorLog(buildDir: string): string {
    const buildOutput = path.join(buildDir, "build", "reports");

    if (fs.existsSync(buildOutput)) {
      // Try to read error report
      try {
        const files = fs.readdirSync(buildOutput, { recursive: true });
        const logFile = files.find(
          (f) => typeof f === "string" && f.endsWith(".txt")
        );
        if (logFile) {
          return fs
            .readFileSync(path.join(buildOutput, logFile as string), "utf-8")
            .slice(-1000);
        }
      } catch (e) {
        // Ignore read errors
      }
    }

    return "See build logs for more details";
  }

  /**
   * Create gradle wrapper script
   */
  private createGradleWrapper(tempDir: string): void {
    const gradlewContent = `#!/bin/bash
# Gradle wrapper stub
exec gradle "$@"`;

    fs.writeFileSync(path.join(tempDir, "gradlew"), gradlewContent, {
      mode: 0o755,
    });

    const batchContent = `@echo off
REM Gradle wrapper stub
gradle %*
exit /b %ERRORLEVEL%`;

    fs.writeFileSync(path.join(tempDir, "gradlew.bat"), batchContent);
  }

  /**
   * Cleanup temporary directory
   */
  private cleanupDirectory(dir: string): void {
    if (fs.existsSync(dir)) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  }

  /**
   * Queue a build if too many are running
   */
  async queueBuild(files: GeneratedFile[], modId: string): Promise<BuildResult> {
    if (this.activeBuildCount >= MAX_CONCURRENT_BUILDS) {
      return new Promise((resolve) => {
        this.buildQueue.push(async () => {
          const result = await this.buildMod(files, modId);
          resolve(result);
          this.processBuildQueue();
          return result;
        });
      });
    } else {
      this.activeBuildCount++;
      try {
        return await this.buildMod(files, modId);
      } finally {
        this.activeBuildCount--;
        this.processBuildQueue();
      }
    }
  }

  /**
   * Process queued builds
   */
  private processBuildQueue(): void {
    if (
      this.buildQueue.length > 0 &&
      this.activeBuildCount < MAX_CONCURRENT_BUILDS
    ) {
      this.activeBuildCount++;
      const buildFn = this.buildQueue.shift();
      if (buildFn) {
        buildFn().catch((e) => console.error("Queued build failed:", e));
      }
    }
  }
}

export interface GeneratedFile {
  path: string;
  content: string | Buffer;
}
